# frozen_string_literal: true

# rabl-extend-compiler extends 'extend' => 61db20e159b13aff40b4e6d7578691e4a952149666ddb64743a5e14f0b36e5e4
#
# This file segment is generated by rabl-extend-compiler rake task
# and should not be edited. To edit the generated extension
# edit the file at: ["extend"]
attributes :id, :derp, :body
# 61db20e159b13aff40b4e6d7578691e4a952149666ddb64743a5e14f0b36e5e4

# Testing multiple extends
# rabl-extend-compiler extends 'extend' => 61db20e159b13aff40b4e6d7578691e4a952149666ddb64743a5e14f0b36e5e4
#
# This file segment is generated by rabl-extend-compiler rake task
# and should not be edited. To edit the generated extension
# edit the file at: ["extend"]
attributes :id, :derp, :body
# 61db20e159b13aff40b4e6d7578691e4a952149666ddb64743a5e14f0b36e5e4
