# frozen_string_literal: true

# rabl-extend-compiler extends 'extend' => f7068853e12dc56fdbd0ca680055426e02196631592ff732735cc972638118cd
#
# This file segment is generated by rabl-extend-compiler rake task
# and should not be edited. To edit the generated extension
# edit the file at: ["extend"]
attributes :id, :body
# f7068853e12dc56fdbd0ca680055426e02196631592ff732735cc972638118cd
